### ISSUE TITLE
Please publish this library on NPM

### ISSUE THREAD

**Issue by laptou** [ycw/three-font-outliner#1]
I'm trying to use this library in Node.js (not in the browser) and it's proving impossible because the `package.json` points to the source files and not the transpiled files, so Node.js always throws an error:

```
/home/laptou/projects/experiments/x/.yarn/$$virtual/three-font-outliner-virtual-d24b1cb46a/0/cache/three-font-outliner-https-9a06a9db86-8818df998d.zip/node_modules/three-font-outliner/src/index.js:1
import Typr from "../lib/Typr/index.js"
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.external_module_.Module._load (/home/laptou/projects/experiments/x/.pnp.js:8561:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/laptou/projects/experiments/x/dist/renderer.js:32:31)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```

**Comment by ycw** [comment]
It seems that the lib is loaded as cjs? (which should be esm);
btw, i don't think it works outside browser because Typr.js & Typr.U.js used `window.` stuff; 
you need to patch those apis yourself. :)
- https://github.com/photopea/Typr.js/blob/3c17ea8b955d4824bf818d5943b96ae3c1a06399/src/Typr.U.js#L958
- https://github.com/photopea/Typr.js/blob/3c17ea8b955d4824bf818d5943b96ae3c1a06399/src/Typr.js#L275

**Comment by laptou** [comment]
Hmm yeah, it seems like this won't work for my use case. I ended up writing my own library based on `opentype.js`. Thanks for looking into it, though!
